[package]
name = "evering-utils"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
local-executor.workspace = true
evering.workspace = true
pin-project-lite.workspace = true
