[package]
name = "evering-ipc"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.98"
local-executor.workspace = true
evering.workspace = true
fastrand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dependencies.argh]
version = "0.1.13"
default-features = false
features = ["help"]

[dependencies.nix]
version = "0.30.1"
features = ["fs", "mman"]
