[package]
name = "io-uring-executor"
version = "0.0.0"
authors = ["Loi Chyan <loichyan@foxmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
pin-project-lite = "0.2.16"
tokio = { version = "1.45.0", features = ["rt", "macros"] }
