[workspace]
members = ["evering", "local-executor"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Loi Chyan <loichyan@foxmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
