[package]
name = "async-client"
version = "0.0.0"
authors = ["Loi Chyan <loichyan@foxmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
