[workspace]
members = ["common", "kernel", "user"]
resolver = "3"

[workspace.package]
version = "0.0.0"
authors = ["Loi Chyan <loichyan@foxmail.com>"]
license = "MIT"
edition = "2024"

[workspace.dependencies]
common = { path = "common" }

# Enable some optimizations in binary crate
[profile.release]
codegen-units = 1
lto = true
strip = true
