[package]
name = "async-crawler"
version = "0.0.0"
authors = ["Loi Chyan <loichyan@foxmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
clap = { version = "4.5.38", features = ["derive"] }
html5ever = "0.31.0"
mime = "0.3.17"
reqwest = "0.12.15"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
trait-variant = "0.1.2"
