name: CICD

on:
  push: { branches: [main] }
  pull_request: {}

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata
        id: metadata
        run: |
          {
            echo toolchain=$(sed -n 's/channel = "\(.*\)"/\1/p' rust-toolchain.toml)
          } | tee -a $GITHUB_OUTPUT

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.metadata.outputs.toolchain }}
      - name: Build docs
        run: cargo doc --no-deps --all-features
      - name: Deploy docs
        if: ${{ github.ref == env.default-branch }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
          single-commit: true
          branch: gh-pages
          folder: target/doc
